### ISSUE TITLE
 yii\base\InvalidParamException: Unrecognized format ''

### ISSUE THREAD

**Issue by mars167** [abei2017/yii2-wx#11]
在`mini/payment/ay.php` 中prepare()方法73行`$response = $this->post(self::PREPARE_URL,$attrs)->setFormat(Client::FORMAT_XML)->send();`发生如下错误
` yii\base\InvalidParamException: Unrecognized format ''`，改为
`$response = $this->post(self::PREPARE_URL,$attrs)->setFormat(Client::FORMAT_XML)->send()->setFormat(Client::FORMAT_XML);`正常，北哥看一下这里吧

**Comment by abei2017** [comment]
感谢发现，已经修正，该问题是yiisoft/yii2-httpclient版本升级导致的问题。
