### ISSUE TITLE
mini template send function got error

### ISSUE THREAD

**Issue by leeyifei** [abei2017/yii2-wx#5]
2018-11-09 01:28:24 [61.160.251.57][17][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: abei2017\wx\mini\template\Template::accessToken in /home/www/yuepai/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /home/www/yuepai/vendor/abei2017/yii2-wx/src/mini/template/Template.php(44): yii\base\Component->__get('accessToken')
#1 /home/www/yuepai/common/services/WechatNotify.php(65): abei2017\wx\mini\template\Template->send('o_DtZ5Cj8oSA39G...', '4IDzASmhL28oPyq...', '', Array)
#2 /home/www/yuepai/common/subscribes/PublishLike.php(70): common\services\WechatNotify->sendLikeNotify(Object(common\modelsext\TablePublishLike))
#3 [internal function]: common\subscribes\PublishLike::sendRemind(Object(yii\db\AfterSaveEvent))
#4 /home/www/yuepai/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\db\AfterSaveEvent))
#5 /home/www/yuepai/vendor/yiisoft/yii2/db/BaseActiveRecord.php(992): yii\base\Component->trigger('afterInsert', Object(yii\db\AfterSaveEvent))
#6 /home/www/yuepai/common/modelsext/TablePublishLike.php(28): yii\db\BaseActiveRecord->afterSave(true, Array)
#7 /home/www/yuepai/vendor/yiisoft/yii2/db/ActiveRecord.php(560): common\modelsext\TablePublishLike->afterSave(true, Array)
#8 /home/www/yuepai/vendor/yiisoft/yii2/db/ActiveRecord.php(515): yii\db\ActiveRecord->insertInternal(NULL)
#9 /home/www/yuepai/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#10 /home/www/yuepai/frontend/modules/api_v1/actions/yue/Like.php(52): yii\db\BaseActiveRecord->save()
#11 [internal function]: frontend\modules\api_v1\actions\yue\Like->run()
#12 /home/www/yuepai/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#13 /home/www/yuepai/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#14 /home/www/yuepai/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('like', Array)
#15 /home/www/yuepai/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('v1/yue/like', Array)
#16 /home/www/yuepai/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#17 /home/www/yuepai/frontend/web/index.php(17): yii\base\Application->run()
#18 {main}

**Comment by leeyifei** [comment]
是不是在小程序的 Template里面加上这段：
private $accessToken = null;

    public function init() {
        parent::init();
        $this->accessToken = (new AccessToken(['conf'=>$this->conf,'httpClient'=>$this->httpClient]))->getToken();
    }

**Comment by abei2017** [comment]
这个bug已经修复，查看最新版本。

**Comment by leeyifei** [comment]
不好意思，是master分支吗？好像还是不行吗，最新版本在哪里啊
