### ISSUE TITLE
文档链接都失效了呢？

### ISSUE THREAD

**Issue by tangniyuqi** [abei2017/yii2-wx#6]
这个项目还维护吗

**Comment by abei2017** [comment]
你好，是的，因为网站更替版本，我马上更新readme。如果急用请从这里先进 http://old.nai8.me/index.php?r=wiki%2Findex&id=1

**Comment by Dzcyr** [comment]
发送模版消息 报错了 已经pull了代码

**Comment by wyc0991** [comment]
http://www.yii2-wx.com/

**Comment by wyc0991** [comment]
http://www.yii2-wx.com/

**Comment by wyc0991** [comment]
http://www.yii2-wx.com/ 又打不开了

**Comment by wyc0991** [comment]
http://www.yii2-wx.com/ 很慢

**Comment by abei2017** [comment]
https://nai8.me/app/book_detail.html?id=8
