### ISSUE TITLE
小程序消息模板获取不到accessToken

### ISSUE THREAD

**Issue by wyc0991** [abei2017/yii2-wx#9]
通过小程序模板消息接口返回：

Getting unknown property: abei2017\\wx\\mini\\template\\Template::accessToken

**Comment by wyc0991** [comment]
测试需要修改gettoken方式
修改 $this->accessToken->getToken()
为：
(new AccessToken(['conf'=>$this->conf,'httpClient'=>$this->httpClient]))->getToken()

**Comment by abei2017** [comment]
你好，在最新的文档中已经支持对于公众号和小程序token的获取，请参考文档。

http://www.yii2-wx.com/wiki/default-index.html?id=1&iid=66
